"""add pipeline_version, audio_offset_sec, module_predictions, visual_window_predictions

Revision ID: 14bc73a6d204
Revises: f617d1a5ed24
Create Date: 2026-08-04 13:48:45.881307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14bc73a6d204'
down_revision: Union[str, None] = 'f617d1a5ed24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('window_sec', sa.Float(), nullable=False),
    sa.Column('index_in_module', sa.Integer(), nullable=False),
    sa.Column('global_start_sec', sa.Float(), nullable=False),
    sa.Column('global_end_sec', sa.Float(), nullable=False),
    sa.Column('predicted_event', sa.String(), nullable=True),
    sa.Column('event_confidence', sa.Float(), nullable=True),
    sa.Column('highlight_score', sa.Float(), nullable=False),
    sa.Column('event_probs', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'module', 'global_start_sec', name='uq_module_prediction_match_module_start')
    )
    op.create_index('ix_module_prediction_match_module_start', 'module_predictions', ['match_id', 'module', 'global_start_sec'], unique=False)
    op.create_table('visual_window_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('tile_index', sa.Integer(), nullable=False),
    sa.Column('window_sec', sa.Integer(), nullable=False),
    sa.Column('clip_start_sec', sa.Float(), nullable=False),
    sa.Column('clip_end_sec', sa.Float(), nullable=False),
    sa.Column('raw_event', sa.String(), nullable=True),
    sa.Column('raw_confidence', sa.Float(), nullable=True),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('softmax', sa.JSON(), nullable=False),
    sa.Column('masked_mass', sa.Float(), nullable=False),
    sa.Column('dropped', sa.Boolean(), nullable=False),
    sa.Column('drop_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visual_window_prediction_match_tile', 'visual_window_predictions', ['match_id', 'tile_index'], unique=False)
    # server_default backfills existing rows as legacy pipeline_version=1;
    # the ORM's Python-side default doesn't apply retroactively to rows already in the table.
    op.add_column('matches', sa.Column('pipeline_version', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('matches', 'pipeline_version', server_default=None)
    op.add_column('matches', sa.Column('audio_offset_sec', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'audio_offset_sec')
    op.drop_column('matches', 'pipeline_version')
    op.drop_index('ix_visual_window_prediction_match_tile', table_name='visual_window_predictions')
    op.drop_table('visual_window_predictions')
    op.drop_index('ix_module_prediction_match_module_start', table_name='module_predictions')
    op.drop_table('module_predictions')
    # ### end Alembic commands ###
