"""add match transcript column

Revision ID: 1da29a8e9ef0
Revises: 14bc73a6d204
Create Date: 2026-08-04 15:45:50.483211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da29a8e9ef0'
down_revision: Union[str, None] = '14bc73a6d204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('transcript', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'transcript')
    # ### end Alembic commands ###
