"""drop legacy v1 tables (segments, module_outputs, fusion_results)

Revision ID: 2819b1b212d5
Revises: 21e959068755
Create Date: 2026-08-05 16:51:13.424993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2819b1b212d5'
down_revision: Union[str, None] = '21e959068755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module_outputs')
    op.drop_table('segments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('match_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('global_start_sec', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('global_end_sec', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('video_chunk_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('audio_chunk_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name='segments_match_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='segments_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('module_outputs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('segment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('module_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], name='module_outputs_segment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='module_outputs_pkey')
    )
    # ### end Alembic commands ###
