"""add fusion_runs, fusion_cells, highlight_clips

Revision ID: 5fc79d54a3d0
Revises: 1da29a8e9ef0
Create Date: 2026-08-04 15:59:57.699960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc79d54a3d0'
down_revision: Union[str, None] = '1da29a8e9ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fusion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('grid_sec', sa.Float(), nullable=False),
    sa.Column('sigmoid_k', sa.Float(), nullable=False),
    sa.Column('commentary_lag_sec', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fusion_cells',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fusion_run_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('cell_index', sa.Integer(), nullable=False),
    sa.Column('global_start_sec', sa.Float(), nullable=False),
    sa.Column('global_end_sec', sa.Float(), nullable=False),
    sa.Column('fused_event', sa.String(), nullable=False),
    sa.Column('fused_event_confidence', sa.Float(), nullable=False),
    sa.Column('fused_score', sa.Float(), nullable=False),
    sa.Column('visual_tile_index', sa.Integer(), nullable=False),
    sa.Column('contributions', sa.JSON(), nullable=False),
    sa.Column('modules_present', sa.JSON(), nullable=False),
    sa.Column('disagreement', sa.Boolean(), nullable=False),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fusion_run_id'], ['fusion_runs.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fusion_run_id', 'cell_index', name='uq_fusion_cell_run_index')
    )
    op.create_index('ix_fusion_cell_run_index', 'fusion_cells', ['fusion_run_id', 'cell_index'], unique=False)
    op.create_table('highlight_clips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('global_start_sec', sa.Float(), nullable=False),
    sa.Column('global_end_sec', sa.Float(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('peak_score', sa.Float(), nullable=False),
    sa.Column('mean_score', sa.Float(), nullable=False),
    sa.Column('source_cell_start', sa.Integer(), nullable=False),
    sa.Column('source_cell_end', sa.Integer(), nullable=False),
    sa.Column('cells', sa.JSON(), nullable=False),
    sa.Column('was_expanded', sa.Boolean(), nullable=False),
    sa.Column('was_trimmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['highlight_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_highlight_clip_job_rank', 'highlight_clips', ['job_id', 'rank'], unique=False)
    op.add_column('highlight_jobs', sa.Column('fusion_run_id', sa.UUID(), nullable=True))
    op.add_column('highlight_jobs', sa.Column('params', sa.JSON(), nullable=True))
    op.add_column('highlight_jobs', sa.Column('total_duration_sec', sa.Float(), nullable=True))
    op.add_column('highlight_jobs', sa.Column('clip_count', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'highlight_jobs', 'fusion_runs', ['fusion_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'highlight_jobs', type_='foreignkey')
    op.drop_column('highlight_jobs', 'clip_count')
    op.drop_column('highlight_jobs', 'total_duration_sec')
    op.drop_column('highlight_jobs', 'params')
    op.drop_column('highlight_jobs', 'fusion_run_id')
    op.drop_index('ix_highlight_clip_job_rank', table_name='highlight_clips')
    op.drop_table('highlight_clips')
    op.drop_index('ix_fusion_cell_run_index', table_name='fusion_cells')
    op.drop_table('fusion_cells')
    op.drop_table('fusion_runs')
    # ### end Alembic commands ###
